### ISSUE TITLE
4.6 Reports UI compatibility issue?

### ISSUE THREAD

**Issue by robbrandt** [eileenmcnaughton/nz.co.fuzion.extendedreport#31]
Eileen, could you report on the status of the report UI compatibility with Civi 4.6?

http://forum.civicrm.org/index.php/topic,35596.0.html

If it's all "working", what version of Civi is it in and what version of ExtendedReports?  It appears that the Civi issue you referenced in the thread was closed in a 4.6 version, but I have 4.6.3 installed and Extended Reports 2.0 along with it, and the problem is still there.

Thanks.

**Comment by eileenmcnaughton** [comment]
Do you have any other reports extensions installed? Report base or Advanced fundraising?

**Comment by robbrandt** [comment]
I don't think so but I will check tomorrow. But I disabled Extended Reports and the UI snapped into place.

**Comment by robbrandt** [comment]
I've just gone through and disabled all the extensions, one by one, and testing the Report UI after each one.  Extended Reports was last, and the UI only snapped into place after I disabled that extension.

There are no other purely reports extensions installed, although some that might/probably have reports with them.  Those would be Mandrill Account Emails and CiviVolunteer.

**Comment by eileenmcnaughton** [comment]
I feel like this is resolved - we are running extended reports on lots of 4.6 sites now - I'm going to close unless you indicate otherwise

**Comment by robbrandt** [comment]
Hi Eileen, we are still having trouble with this one.  Users complaining again.  I just updated to v2.1 (Civi 4.6.9) and the problem is still there.

The testing I have done is with standard, out of the box reports - not extended reports.  But those reports start working when Extended Reports is disabled.  And they keep working until Extended Reports is enabled.  Any idea what would cause the tab system to collapse?

**Comment by robbrandt** [comment]
It works!  I completely deleted the extendedreports folder and uploaded it again, and the problem has gone away.  Should have tried that long ago.  I guess there was some artifact in there from an old revision that was causing a problem.

**Comment by eileenmcnaughton** [comment]
ah yeah - file overrides that were removed from the extension but would not have been deleted by upgrading maybe
